spring:
  application:
    name: zhymc-eureka:peer1
  profiles:
    active: peer1

server:
  port: 8000

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8001/eureka/
    fetch-registry: false
    register-with-eureka: false